### ISSUE TITLE
Dev Model

### ISSUE THREAD

**Issue by krischer** [chukren/pyadjoint#3]
Hi guys,

I noticed you added a lot of commits to this fork's `dev` branch. This makes it really hard for me to review things and merge it back in to the main repository. I think it would be much better if you just make small changes and submit individual PRs to the main repository. This makes is simpler to review and discuss the changes and finally merge them. Also we don't end up with two diverging repositories. I added you as collaborators to the original repository so you should have all required rights to do everything you need.

Cheers!

Lion

**Comment by chukren** [comment]
Hi Lion,

Thank you for open the access of master branch for me to request pulls.  Yes, I have to admit that I create a huge mess by making a lot of changes recently and we are still racing with time to benchmark and test it for our tomography workflow.  I will sum up all the major changes I made later this week and hope you will be available for a  Skype call to discuss about the changes. Thank you very much. 

Best,

Youyi

**Comment by krischer** [comment]
Great :-) Also feel free to directly push to the main repository. I just would really like to avoid diverging repositories.

In general I also rather dislike having a `devel`/`dev` branch. Its best to either work directly in master or in smallish feature branches. But having a `devel` branch and periodically merging it back in master which in the meantime might have advanced results in nasty merging issue. If you want a stable thing for users, just tag a commit and point them to it.

**Comment by chukren** [comment]
Hi Lion,

With help from Wenjie and Matthieu, I think I am ready to merge my branch to master, although is not well written at least it's been benchmark and tested with real data.  So I may need to schedule a time to skype with you to figure out how to merge my mess to master.

BTW, the major changes are list below,
1, Add a config file to remove the hard-coded parameters from multi-taper (mt) misfit and cross correlation (c. c.) misfit.
2, Restructured multi-taper misfit functions. Fixed bug in transfer function estimation and adjoint source calculation.  Add safe guard for multi-taper adjoint source source.  
3, Adjust the input of calculated_adjoint_source() to handle multiple windows for each trace, and testing function and plotting function accordingly
4, Add adjoint sources for amplitudes in c.c. and mt misfit
5, Add few taper functions in util to benchmark the ones used in measure_adj, and to handle the needs for multiple windows in one trace.
6, Add logger for debug and warning.

To do list,
1, As wenjie suggested, I need to write a configbase to host the config file for c.c., multi-taper, and waveform, and later Yanhua's double-difference adjoint source
2, Since multi-taper adjoint source will automatically switch to cross correlate adjoint source for any window failed the selecting criteria, so I just replicate the c.c. code in mt code, which may need to 
be considered and re-designed later.

**Comment by krischer** [comment]
Heyhey,

I have some time this Thursday/Friday. Any chance you are available for a skype? I'll have a look at the code by then.

**Comment by chukren** [comment]
@krischer Thanks Lion! I should be available on Thursday after group meeting around 10:30am (3:30pm in Munich) or Friday before 10:30am and after 11:30 am. Please let me know when would work best for you.

**Comment by krischer** [comment]
3:30 pm Munich time works for me. See you then!

**Comment by chukren** [comment]
dev branch has been merged to master and shall be removed.
